CC = gcc
CFLAGS = -Wall -Wextra -Wno-unused-parameter -std=gnu11 -O3
LDLIBS = -lm

PROGRAMS = allchar allutf8 allcolor order cmpsus sizeof typedef parser sizes wex

make:	$(PROGRAMS)

clean:
		rm -f $(PROGRAMS)
