// sizes.c
// various tests to look as sizes generated by compiler
// 2016-07-04	PV

#include <stdio.h>
#include <stdlib.h>

#define ts(x) printf("sizeof(" #x "): %u\n", sizeof(x))

// Bu default, each field is aligned on itys type size
struct RGB565_a {
	unsigned char r: 5;
	unsigned char g: 6;
	unsigned char b: 5;
};

#pragma pack(1)
struct RGB565_b {
	unsigned char r: 5;
	unsigned char g: 6;
	unsigned char b: 5;
};

char a[10000]; 

int main() {
	ts(char);
	ts(short);
	ts(int);
	ts(long);
	ts(long long);

	ts(float);
	ts(double);
	ts(long double);

	ts(char *);
	ts(void *);
	ts(const signed long int volatile *((*)()));

	ts(struct RGB565_a);
	ts(struct RGB565_b);

	ts(a);

	return 0;
}
