CC = gcc
CFLAGS = -lm

PROGRAMS = fbtest6 fbtestXX fbtestXII font/fbtestfnt fbtest5z fbtestX fbtestXIV fbtest5x fbtest5y fbtest7 fbtest8b fbfire fbtestXIII fbtestXIVb fbtest8

make:	$(PROGRAMS)

clean:
		rm -f $(PROGRAMS)
