
fb6hil:	fb6hil.c
		gcc -time -fdump-rtl-all-slim-stats -dA -dD -dP -fdump-tree-all-details-stats -fdump-ipa-all -fdump-statistics-details -std=gnu11 -O3 fb6hil.c -lm -o fb6hil

clean:
		rm -f fb6hil.c.* fb6hil
